name: Build site

on:
    push:
        branches: ["develop"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow running git push
permissions:
    contents: write

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build docker image
              run: docker compose build

            - name: Build CSS
              run: docker compose run css /tailwindcss -i ./styles.css -o ./dist/styles.css --minify

            - name: Build static
              run: docker compose run static /venv/bin/python watch_static.py --build

            - name: Build HTML
              run: docker compose run templates /venv/bin/python watch_templates.py --build

            - name: Push to main
              run: |
                  TMP=$(mktemp --directory)
                  cp -r dist/* "$TMP"/
                  git checkout main

                  rm -rf ./*
                  cp -r "$TMP"/* ./
                  echo 'www.mayortech.co.uk' > CNAME

                  git config --global user.name 'William Mayor'
                  git config --global user.email 'WilliamMayor@users.noreply.github.com'
                  git add .
                  D=$(date +"%Y-%m-%dT%H:%M:%S")
                  git commit -m "Deploy on $D"
                  git push origin main
